let scriptureMatrix = [
{Evil: [{sun: 'Psalm 105:1,3\n"O give thanks to the Lord, call upon His name. Make known His deeds among the people. Let the heart of those who seek the Lord be glad."'}, 
        {mon: '3 John 1:11\n"Beloved, do not imitate what is evil, but what is good. The one who is good is of God. The one who does evil has not seen God."'},
        {tue: 'Matthew 6:13\n"And do not lead us into temptation, but deliver us from evil."'}, 
        {wed: 'Proverbs 8:7\n"For my mouth will utter truth and wickedness is an abomination to my lips."'},
        {thu: 'John 3:20\n"For everyone who does evil hates the light, and does not come to the light, lest his deeds should be exposed."'}, 
        {fri: '1 Chronicles 16:34\n"O give thanks to the Lord for He is good; for His lovingkindness is everlasting."'},
        {sat: 'Psalm 95:2-3\n"Let us come before the Lord\'s presence with thanksgiving, let us shout joyfully to Him with psalms. For the Lord is a great God and a great King above all gods."'},
        {bonus: '1 Thessalonians 1:3\n"We ought always to give thanks to God for you brethren...your faith is greatly enlarged and the love of each one of you towards one another grows even greater."'}]},
{Forgiveness: [
        {sun: 'Psalm 86:5\n"For you, Lord, are good and ready to forgive, and abundant in lovingkindness to all who call upon You."'}, 
        {mon: '1 John 1:9\n"If we confess our sins, He (God) is faithful and righteous to forgive us our sins, and to cleanse us from all unrighteousness."'},
        {tue: 'Matthew 6:12\n"And forgive us our moral debts as we also have forgiven our moral debtors."'}, 
        {wed: 'Matthew 6:14\n"For if you forgive men for their transgressions, your heavenly Father will also forgive you."'},
        {thu: 'Ephesians 4:32\n"And be kind to one another, tender hearted, forgiving each other, just as God in Christ also has forgiven you."'}, 
        {fri: 'Luke 23:34\n"But Jesus was saying, \'Father forgive them; for they do not know what they are doing.\' And they cast lots, dividing up His garments among themselves."'},
        {sat: 'Matthew 18:21-22\n"Then Peter came to Jesus and said, \'How often shall my brother sin against me, and I forgive him? Up to seven times?\' Jesus said, \'Up to seventy times seven.\'"'}]},
{Happiness: [
        {sun: '1 Chronicles 16:10\n"Glory in His holy name, let the heart of those who seek the Lord be glad."'}, 
        {mon: 'Proverbs 16:20\n"Blessed (happy) is he who trusts in the Lord."'},
        {tue: 'Romans 15:13\n"Now may the God of hope fill you with all joy and peace."'}, 
        {wed: 'Proverbs 14:21\n"Happy is he who is gracious to the poor."'},
        {thu: 'Psalm 132:9\n"Let your Godly people sing for joy."'}, 
        {fri: 'Psalm 144:5\n"How blessed (happy) are the people whose God is the Lord."'},
        {sat: 'Proverbs 29:18\n"Happy is he who keeps the law (God\'s Commandments)."'}]},
{Ark: [
        {sun: "Genesis 1:31\nThen God looked over all He had made, and He saw that it was very good."}, 
        {mon: "Romans 6:13\nSurrender your whole being to God to be used for righteous purpose."},
        {tue: "Isaiah 30:15\nIn repentance and rest is your salvation, in quietness and trust is your strength."}, 
        {wed: 'John 7:37\nJesus stood and cried out, "If anyone thirsts, let him come to Me and drink." (living water)'},
        {thu: "Proverb 23:17\nDo not let your heart envy sinners, but live in fear of the Lord."}, 
        {fri: "Proverb 21:23\nHe (the person) who guards his/her tongue guards their soul from trouble."},
        {sat: "1 John 4:16\nAnd so we know and rely on the love God has for us. God is love."}]},
{Worship: [
        {sun: "Psalm 2:11\nWorship the Lord with reverence and rejoice with trembling."}, 
        {mon: "Psalm 66:4\nAll the earth will worship You (God), and will sing praises to You."},
        {tue: "Isaiah 29:13\nPeople honor Me with their lips but their heart is far away from Me."}, 
        {wed: "John 4:24\nGod is spirit and those who worship Him must worship in spirit and truth."},
        {thu: "Exodus 34:14\nFor you shall not worship any other god, for the Lord, whose name is Jealous is a jealous God."}, 
        {fri: 'Matthew 4:10\nJesus said,"Begone Satan, for it is written: you shall worship the Lord your God, and serve Him only."'},
        {sat: "Revelation 4:11\nWorthy are You our Lord and our God, to receive glory and honor and power for You created all things."}]},
{Promise: [
        {sun: "Revelation 10:1\nI saw another strong angel coming down out of heaven, clothed with a cloud and the rainbow was upon his head."}, 
        {mon: "2 Peter 3:13\nBut according to His (God\'s) promise, we are looking for new heavens and a new earth in which righteousness dwells."},
        {tue: "Psalm 29:2\nHonor the Lord in the glory. due His name; worship the Lord in the splendor of His holiness."}, 
        {wed: "Psalm 112:1,2\nPraise the Lord. How blessed is the man (person) who fears the Lord who greatly delights in His commandments, his descendants will be mighty on earth. The generations of the upright will be blessed."},
        {thu: "Genesis 8:21\nGod said, will never again curse the ground on account of man for the intent of Man\'s heart is evil and I will never again destroy every living thing as I have done."}, 
        {fri: 'Genesis 9:11\nI establish My covenant with you and all flesh shall never again be cut off by water of the flood."'},
        {sat: "Revelation 4:3\nAnd He who was sitting on the throne was like a jasper stone (crystal clear) and a sardius (blood red) in appearance, and there was a rainbow around the throne like an emerald in appearance."}]},
{Pray: [
        {sun: 'Matthew 21:21-22\n"And Jesus answered and said to them, \'If you have faith, and do not doubt...everything you ask in prayer, believing, you shall receive.\'"'}, 
        {mon: 'Colossians 4:2\n"Devote yourself to prayer, keeping alert in it with an attitude of thanksgiving."'},
        {tue: 'Matthew 6:6\n"When you pray go into your inner room...shut your door, pray to your Father who is in secret, and your Father...will repay you."'}, 
        {wed: 'Matthew 5:44\n"But I say to you, \'Love your enemies and pray for those who persecute you.\'"'},
        {thu: 'Psalm 4:1\n"Answer me when I call O God of my righteousness, and God\'s ears attend to my prayer."'}, 
        {fri: '1 Thessalonians 5:17\n"Pray without ceasing."'},
        {sat: '1 Samuel 2:1\n"Then Hannah prayed and said, \'My heart exalts in the Lord...because I rejoice in Your salvation.\'"'}]},
{Spirit: [
        {sun: 'Titus 3:6\n"For God abundantly poured out the Holy Spirit on us through Jesus Christ our Savior."'}, 
        {mon: '2 Timothy 1:14\n"Keep the good things that have been entrusted to you, through the power of the Holy Spirit who lives in us."'},
        {tue: 'Mark 1:18\n"I, John the Baptist baptize you with water, but Jesus will baptize you with the Holy Spirit."'}, 
        {wed: '1 John 4:2\n"This is how you will know it is God\'s Spirit: everyone who declares that Jesus Christ became mortal man has the Spirit Who comes from God."'},
        {thu: '1 John 4:13\n"This is how we are sure that we live in God and He lives in us: He has given us His Spirit."'}, 
        {fri: 'Ephesians 4:30\n"Do not grieve God\'s Holy Spirit, for the Spirit is God\'s ownership on you, a guarantee that the day will come when God sets you free."'},
        {sat: 'Galatians 5:25\n"The Spirit has given us life: He must also control our lives."'}]},
{Study: [
        {sun: '1 Corinthians 1:18\n"For the Word of the cross is to those who are perishing foolishness; but to us who are being saved it is the power of God."'}, 
        {mon: '2 Timothy 3:16\n"All Scripture is inspired by God and profitable for teaching, reproof, correction, for training in righteousness that the man of God may be adequately equipped for every good work."'},
        {tue: '2 Peter 1:20-21\n"But know this first of all, that no prophesy of Scripture is a matter of one\'s own interpretation, for no prophesy was ever made by an act of human will, but men moved by the Holy Spirit spoke from God."'}, 
        {wed: 'Psalm 119:11\n"Your Word, Lord, I have treasured in my heart, that I may not sin against you."'},
        {thu: 'Isaiah 55:11\n"So shall My Word be which goes from my mouth; it shall not return to Me empty."'}, 
        {fri: 'Matthew 4:4\n"But He (Jesus) answered and said, \'Man shall not live on bread alone, but on every word that proceeds out of the mouth of God.\'"'},
        {sat: 'Matthew 25:13\n"Watch therefore, for you know neither the day nor the hour in which the Son of Man is coming."'}]},
{Sword: [
        {sun: 'Ephesians 6:18\n"With all prayer and petition, PRAY at all times in the SPIRIT, with this in view, be on the alert with all perseverance and petition for all the saints."'}, 
        {mon: 'Ephesians 6:11\n"Put on the full ARMOR of God, that you may be able to stand firm against the schemes of the devil."'},
        {tue: 'Ephesians 6:14\n"Having girded your loins with TRUTH."'}, 
        {wed: 'Ephesians 6:14\n"Having put on the breastplate of RIGHTEOUSNESS."'},
        {thu: 'Ephesians 6:15\n"Having shod your feet with the preparation of the good news of PEACE."'}, 
        {fri: 'Ephesians 6:16\n"In addition to all, taking up the SHIELD OF FAITH."'},
        {sat: 'Ephesians 6:17\n"And take the HELMET OF SALVATION and the SWORD OF THE SPIRIT, which is the WORD OF GOD."'}]},
{Thankful: [
        {sun: 'Psalm 105:1,3\n"O give thanks to the Lord, call upon His name. Make known His deeds among the people. Let the heart of those who seek the Lord be glad."'}, 
        {mon: 'Psalm 9:1\n"I will give thanks to the Lord with all my heart. I will tell of all Your wonders. I will be glad and exalt in You. I will sing praise to Your name, O Most High."'},
        {tue: 'Psalm 7:17\n"I will give to the Lord according to His righteousness and will sing praise to the name of the Lord Most High."'}, 
        {wed: 'Romans 6:17\n"But thanks be to God that though you were slaves to sin, you became obedient from the heart to that form of teaching to which you were committed."'},
        {thu: 'Ephesians 5:20\n"Always giving thanks for all things in the name of our Lord Jesus Christ to God even the Father."'}, 
        {fri: '1 Chronicles 16:34\n"O give thanks to the Lord for He is good; for His lovingkindness is everlasting."'},
        {sat: 'Psalm 95:2-3\n"Let us come before the Lord\'s presence with thanksgiving, let us shout joyfully to Him with psalms. For the Lord is a great God and a great King above all gods."'},
        {bonus: '1 Thessalonians 1:3\n"We ought always to give thanks to God for you brethren...your faith is greatly enlarged and the love of each one of you towards one another grows even greater."'}]},
{Think: [
        {sun: 'TRUTH\nPsalm 145:18\n"The Lord is near to all who call upon Him, to all who call upon Him in TRUTH."'}, 
        {mon: 'HONESTY\nLuke 8:15\n"But the seed in the good soil, these are the ones who have heard the word in an HONEST and good heart, and hold it fast and bear fruit with perseverance."'},
        {tue: 'RIGHT\nPsalm 19:8\n"The precepts of the Lord are RIGHT, rejoicing the heart."'}, 
        {wed: 'PURITY\n1 Timothy 1:5\n"But the goal of our instruction is love from a PURE heart and a good conscience and a sincere faith."'},
        {thu: 'LOVELY\nIsaiah 52:7\n"How LOVELY on the mountains are the feet of him who brings good news, who announces peace and brings good news of happiness, and who announces salvation...your God reigns!"'}, 
        {fri: 'GOOD REPUTE\nJohn 12:36-38\n"These things Jesus spoke,...But though He had performed so many signs before them, yet they were not believing in Him...Lord, who has believed our REPORT?"'},
        {sat: 'EXCELLENCE\n1 Peter 2:9\n"But you are a chosen race, a royal priesthood, a holy nation, a people for God\'s own possession so that you may proclaim the EXCELLENCE of Him."'},
        {bonus: 'PRAISE\nPsalm 103:1\n"BLESS the Lord O my soul; and all that is within me, BLESS His Holy Name."'}]},
{Time: [
        {sun: 'Hebrews 3:15\n"Today, if you hear his voice, do not harden your hearts as in the rebellion."'}, 
        {mon: 'Psalm 90:4\n"For a thousand years in Your sight are like yesterday when it passes by, or as a watch in the night."'},
        {tue: 'Ecclesiastes 3:1,3\n"There is an appointed time for everything. And there is a time for every event under heaven — A time to weep and a time to laugh;"'}, 
        {wed: 'Psalm 90:10\n"As for the days of our life, they contain seventy years, Or if due to strength, eighty years, Yet their pride is but labor and sorrow; For soon it is gone and we fly away."'},
        {thu: 'James 4:14\n"Yet you do not know what your life will be like tomorrow. You are just a vapor that appears for a little while and then vanishes away."'}, 
        {fri: 'Hebrews 9:27\n"And inasmuch as it is appointed for men to die once and after this comes judgment,"'},
        {sat: 'Psalm 139:16\n"Your eyes have seen my unformed substance; And in Your book were all written the days that were ordained for me,"'},
        {bonus: 'Psalm 103:1\n"BLESS the Lord O my soul; and all that is within me, BLESS His Holy Name."'}]},
{Hope: [
        {sun: 'Romans 5:5\n"And HOPE does not disappoint, because the love of God has been poured out within our hearts through the Holy Spirit Who was given us."'}, 
        {mon: '1 Peter 1:13\n"Therefore, with minds that are alert and fully sober, set your HOPE on the grace to be brought to you when Jesus Christ is revealed at His coming."'},
        {tue: 'Romans 8:24\n"For in HOPE we have been saved, but HOPE that is seen is not HOPE...but if we HOPE for what we do not see, with perseverance we wait eagerly for it."'}, 
        {wed: 'Titus 2:12-13\n"Instructing us to deny ungodliness...looking for the blessed HOPE and the appearing of the glory of our great God and Savior Christ Jesus."'},
        {thu: 'Romans 15:13\n"Now may the God of HOPE fill you with all joy and peace in believing that you may abound in HOPE by the power of the Holy Spirit."'}, 
        {fri: 'Psalm 130:5\n"I wait for the Lord, my soul does wait, and in His word do I HOPE."'},
        {sat: 'Psalm 33:18\n"But the eyes of the Lord are on those who fear Him, on those whose HOPE is in His unfailing love."'},
        {bonus: '1 Peter 3:15\n"But set apart Christ Jesus in your heart, always being ready to give a reason to everyone who asks you to give an account for the HOPE that is in you."'}]},
{Faith: [
        {sun: 'Romans 10:17\n"So faith comes from hearing, and hearing by the word of Christ."'}, 
        {mon: 'Habakkuk 2:4\n"Behold as for the proud one, his soul is not right within him. But the righteous will live by his faith."'},
        {tue: 'Romans 3:21\n"But now the righteousness of God apart from the law is revealed...through faith in Jesus Christ, to all and on all who believe."'}, 
        {wed: 'Ephesians 2:8\n"For by grace we have been saved by faith, and that not of yourself, it is a gift from God."'},
        {thu: 'James 1:2-3\n"Consider it all joy my brethren when you encounter various trials, knowing that the testing of your faith produces endurance."'}, 
        {fri: 'Hebrews 10:3\n"By faith we understand that the worlds were prepared by the word of God, so that what is seen was not made out of things which are visible."'},
        {sat: '2 Corinthians 13:5\n"Test yourselves to see if you are in the faith, examine yourselves! Jesus Christ is in you unless you fail the test."'},
        {bonus: 'Psalm 103:1\n"BLESS the Lord O my soul; and all that is within me, BLESS His Holy Name."'}]},
{Love: [
        {sun: '1 John 3:16\n"This is how we know what love is: Christ gave His life for us."'}, 
        {mon: '1 Peter 2:17\n"Respect all men, love your fellow believers, fear God and respect the [rulers]."'},
        {tue: '1 John 4:7	\n"Dear friends, let us love one another, for love comes from God."'}, 
        {wed: 'Romans 8:35,37\n"Who shall separate us from the love of Christ? Shall trouble or hardship or persecution or famine or nakedness or danger or sword? No, in all these things we are more than conquerors through him who loved us."'},
        {thu: '1 Corinthians 2:9\n"What eye has not seen, and ear has not heard, and what has not entered the human heart, what God has prepared for those who love him"'}, 
        {fri: '1 John 2:15\n"Do not love the world or the things of the world. If anyone loves the world, the love of the Father is not in him."'},
        {sat: '1 John 4:7	\n"Dear friends, let us love one another, because love comes from God. Whoever loves is a child of God and knows God."'},
        {bonus: '2 John 6\n"This love I speak of means that we must live in obedience to God\'s commands."'}]},
{Letters: [
        {sun: 'Romans 5:8\n"But God demonstrates His own love toward us, in that while we were yet sinners, Christ died for us."'}, 
        {mon: 'Leviticus 19:18\n"You shall not take vengeance, nor bear any grudge but you shall love your neighbor as yourself, I am the Lord."'},
        {tue: 'Colossians 3:19\n"Husbands love your wives, and do not be embittered against them."'}, 
        {wed: '2 Corinthians 9:7\n"Let each one do just as he has purposed in his heart, not grudgingly or under compulsion. God loves a cheerful giver."'},
        {thu: '1 Corinthians 2:9\n"Eye has not seen, nor ear heard, nor have entered into the heart of man the things which God has prepared for those who love Him."'}, 
        {fri: 'Proverbs 3:12\n"For whom the Lord loves he reproves, even as a father, the son in whom he delights."'},
        {sat: 'John 3:16\n"For God so loved the world that He gave His only Son, that whoever believes in Him should not perish, but have eternal life."'},
        {bonus: '2 Timothy 1:7\n"For God has not given us a spirit of timidity, but of power and love and discipline."'}]},
{Grace: [
        {sun: 'Proverbs 3:34\n"Though He (God) scoffs at the scoffers, yet He gives grace to the afflicted."'}, 
        {mon: 'Luke 2:40\n"The child (Jesus) continued to grow and become strong increasing in wisdom and the grace of God."'},
        {tue: 'John 1:17\n"For the law was given through Moses; grace and truth were realized through Jesus Christ."'}, 
        {wed: 'Romans 5:12, 15b\n"Sin came into the world through one man (Adam), and his sin brought death with it. But God\'s grace is much greater. So is His free gift to men through the grace of one man Jesus Christ."'},
        {thu: '2 Peter 3:18\n"But grow in the grace and knowledge of our Lord and Savior Jesus Christ."'}, 
        {fri: 'Hebrews 4:16\n"Let us therefore draw near with confidence to the throne of grace, that we may receive mercy and may find grace to help in times of need."'},
        {sat: '2 Corinthians 12:9\n"My (God\'s) grace is sufficient for you, for power is perfected in your weaknesses."'},
        {bonus: 'Romans 5:20\n"The law came in so that the transgression would increase, but where sin increases My grace increases all the more."'}]},
{Wisdom: [
        {mon: 'Proverbs 9:10\n"The fear (awe) of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding."'},
        {tue: 'Matthew 11:19\n"Yet wisdom is vindicated by her deeds."'}, 
        {wed: '2 Timothy 3:15\n"From childhood you have known the Sacred Scriptures which are able to give you the wisdom that leads to salvation through faith which is in Jesus Christ."'},
        {thu: 'James 1:5\n"But if any of you lacks wisdom, let him ask of God, Who gives to all men generously without reproach."'}, 
        {fri: 'Proverbs 1:7\n"Do not be wise in your own eyes; Fear the Lord and turn away from evil."'},
        {sat: 'Proverbs 2:2\n"Make your ear attentive to wisdom. Incline your heart to understanding."'},
        {sun: '1 Corinthians 2:5-6\n"Your faith should not rest on the wisdom of men, but on the power of God. Yet we do speak wisdom among those who are mature."'},
        {bonus: '1 Corinthians 1:19-20\n"It is written, I (the Lord) will destroy the wisdom of the wise, and the cleverness of the clever I will set aside ... Has not God made foolish the wisdom of the world?"'}]},
{Resurrection: [
        {mon: 'Matthew 9:36\n"Seeing the people, He (Jesus) felt compassion for them, because they were distressed and dispirited like sheep without a shepherd."'},
        {tue: 'Romans 9:33\n"Just as it is written (Isaiah 28:16), Behold, I lay in Zion a Stone of Stumbling and a Rock of Offense, and he who believes in Him will not be put to shame."'}, 
        {wed: 'In Mark 14:17-31, Jesus institutes the Lord\'s supper with bread and wine. He reveals His blood is being shed for the forgiveness of sin for many. And our Savior announces that one would betray Him while one would deny Him three times'},
        {thu: 'Luke 22:14-15\n"And when the hour had come He reclined at table and the Apostles with Him, and He said to them, I have earnestly desired to eat this passover with you before I suffer."'}, 
        {fri: 'Mark 15:24\n"And they crucified Him, and divided up His garments among themselves casting lots for them, to decide what each would take."'},
        {sat: 'In Luke 23:50-56, a man asked for the body of Jesus. He took it down, wrapped it in linen cloth, laid it in a tomb. Women who had come with Him from Galilee followed after.'},
        {sun: 'Matthew 28:5,6,20\n"The angel said to the women, \'Do not be afraid, for I know that you are looking for Jesus, who was crucified. He is not here; he has risen, just as he said. Come and see the place where he lay.\'" "and teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age."'},
        {bonus: 'Matthew 21:9\n"The crowds going ahead of Him, and those who followed were shouting \'Hosanna to the Son of David: Blessed be He who comes in the name of the Lord, Hosanna in the highest!\'"'}]}, 
{Obey: [
        {mon: 'Deuteronomy 27:10\n"You shall therefore obey the Lord your God, and do His commandments and His statutes, which I (Moses) command you today."'},
        {tue: 'Hebrews 13:17\n"Obey your (church) leaders and submit to them, for they keep watch over your souls."'}, 
        {wed: 'Philippians 2:8\n"And being found in appearance as a man, He (Jesus) humbled Himself by becoming obedient to the point of death, even death on a cross."'},
        {thu: 'Matthew 8:27\n"And the men marveled saying, What kind of man is this, that even the winds and the sea obey Him (Jesus)?"'}, 
        {fri: 'Acts 5:29\n"But Peter and the apostles answered, and said, We must obey God rather than men."'},
        {sat: '2 Corinthians 2:9\n"For to this end I wrote that I might put you to the test, whether you are obedient in all things."'},
        {sun: 'Hebrews 5:8\n"Although He was a Son (Jesus), He learned obedience from the things He suffered having been made perfect. Hebe came to all who obey Him the source of eternal salvation."'},
        {bonus: '1 Peter 1:22\n"Since you have in obedience to the truth purified your soul for a sincere love of the brethren, fervently love one another from the heart."'}]},
{Prayer: [
        {mon: 'Matthew 6:9a\n"Our Father who is in heaven:"\n\n<i>Think about having a father who is king.</i>'},
        {tue: 'Matthew 6:9b\n"Hallowed be Your name,"\n\n<i>Think about the importance of a name - an identity.</i>'}, 
        {wed: 'Matthew 6:10a\n"Your kingdom come."\n\n<i>Think about what God\'s Kingdom is like.</i>'},
        {thu: 'Matthew 6:10b\n"Your will be done"\n\n<i>Think about what is God\'s will for His people.</i>'}, 
        {fri: 'Matthew 6:10c\n"On earth as it is in heaven."\n\n<i>Think about heaven\'s beauty and earth\'s beauty.</i>'},
        {sat: 'Matthew 6:11\n"Give us this day our daily bread."\n\n<i>Think about what bread represents.</i>'},
        {sun: 'Matthew 6:12\n"Forgive us our debts as we have forgiven our debtors."\n\n<i>Think about forgiveness; how many times should we forgive?</i>'},
        {bonus: 'Matthew 6:13\n"Do not lead us into temptation, but deliver us from evil."\n\n<i>Think about what is your temptation? Who is the Evil One?</i>'}]},
{Patriotic: [
        {mon: 'John 8:32\n"And you shall know the truth, and the truth will make you free."'},
        {tue: 'Luke 8:15\n"And the seeds in the good ground, these are the ones who have heard the Word in an honest and good heart."'}, 
        {wed: 'Proverbs 28:5\n"Evil men do not understand justice, but those who seek the Lord understand all things."'},
        {thu: 'Luke 20:25\n"Then render to Caesar the things that are Caesar\'s, and to God the things that are God\'s."'}, 
        {fri: 'Philemon 21\n"Having confidence in your obedience I write to you, knowing that you will do even more than I say."'},
        {sat: 'Psalm 19:7\n"The law of the Lord is perfect, converting the soul."'},
        {sun: 'Psalm 33:12\n"Blessed is the nation where God is Lord."'},
        {bonus: 'Psalm 119:45\n"And I will walk toward liberty. For I seek God\'s precepts!"'}]},
{Reborn: [
        {mon: 'John 3:16\n"For God so loved the world, that He gave His only Son, that whoever believes in Him (Jesus) should not perish, but have eternal life."'},
        {tue: 'John 3:3, 5\n"Truly, truly I say to you, Unless one is born again, he cannot see the kingdom of God. Truly, truly ... unless one is born of water and of the Spirit, he cannot enter into the kingdom of heaven."'}, 
        {wed: 'Revelation 3:20\n"Behold. I (Jesus) stand at the door and knock if anyone hears My voice and opens the door, I will come in to him, and dine with him, and he with me."'},
        {thu: 'Romans 3:23\n"For all have sinned and fall short of the glory of God, being justified as a gift by His grace through redemption, which is for Christ."'}, 
        {fri: 'Romans 6:23\n"For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."'},
        {sat: 'Romans 10:9\n"that if you confess with your mouth that Jesus is old and believe in your heart that God raised Him from the dead, you shall be saved."'},
        {sun: 'Ephesians 2:8\n"For by grace you have been saved through faith; and that not of yourselves, it is a gift of God; not as a result of works, so that no one may boast."'},
        {bonus: 'Isaiah 55:6, 7b\n"Seek the Lord while He may be found. Call upon Him while He is near ... for God will abundantly pardon."'}]},
{Promises: [
        {mon: 'Romans 10:17\n<span>"So <u>faith</u> comes from hearing and hearing by the word of Christ."</span>'},
        {tue: '1 Corinthians 15:33\n<span>"Do not be deceived. Bad corrupts good <u>morals</u>."</span>'}, 
        {wed: 'Romans 11:33\n<span>"Oh, the depth of the riches both of the wisdom and <u>knowledge</u> of God!"</span>'},
        {thu: 'Acts 24:24-25\n<span>"Felix arrived with Drusilla, his wife. And sent for Paul, and heard Paul speak about faith in Jesus Christ... he was discussing <u>self-control</u>. Felix became frightened."</span>'}, 
        {fri: 'Romans 15:4\n<span>"For whatever was written in earlier times was written for our instruction, that through <u>perseverance</u> and the encouragement of Scriptures we might have hope."</span>'},
        {sat: '1 Timothy 3:16\n<span>"And by common confession great is the mystery of <u>godliness</u>."</span>'},
        {sun: '1 Peter 2:2-3\n<span>"Like newborn babes ... you may grow in respect to salvation if you have tasted the <u>kindness</u> of the Lord."</span>'},
        {bonus: 'Ephesians 3:19\n<span>"And to know the <u>love of Christ</u> which surpasses knowledge, that you may be filled up to all the fullness of God."</span>'}]},
{Satan: [
        {mon: 'Luke 10:18\n"And He (Jesus) said to them (the seventy disciples), I was watching Satan fall from heaven like lightning."'},
        {tue: 'Ephesians 6:11-12\n"Put on the full armor of God, so that you will be able to stand firm against the schemes of the devil."'}, 
        {wed: 'Ephesians 2:1-2\n"And you were dead in your trespasses and sins ... according to the prince of the power of the air. ... that is now working in the sons of disobedience."'},
        {thu: 'John 8:44\n"You are of your father the devil, and you want to do the desires of your father."'}, 
        {fri: '1 Peter 5:8\n"Be sober, be vigilant, because your adversary the devil walks about like a roaring lion, seeking whom he may devour."'},
        {sat: 'John 13:2\n"During supper, the devil having already put into the heart of Judas Iscariot, the son of Simon, to betray Him (Jesus)."'},
        {sun: 'Isaiah 14:12-13\n"You (Satan) have fallen from heaven, ...and said in your heart, I will ascend to heaven, I will raise my throne above the stars of God. I will make myself like the Most High."'},
        {bonus: 'Revelation 20:10\n"And the devil who deceived them (the nations) was thrown into the lake of fire and brimstone ... and will be tormented day and night forever and ever."'}]},
{Harvest: [
        {mon: 'Matthew 9:37\n"Then Jesus said to His disciples "The harvest truly is plentiful, but the laborers are few.""'},
        {tue: 'Isaiah 9:3\n"You have multiplied the nation and increased its joy. They rejoice before you according to the joy of harvest."'}, 
        {wed: 'Matthew 9:38\n"Therefore pray the Lord of the harvest to send out laborers into His harvest."'},
        {thu: 'Jeremiah 8:20\n"The harvest is past, the summer is ended. And we are not saved."'}, 
        {fri: 'Genesis 8:21-22\n"The Lord said, I will never again curse the ground... while the earth remains, Seedtime and Harvest, Cold and Heat, Winter and Summer, Day and Night, shall not cease!"'},
        {sat: 'Proverbs 10:5\n"He who gathers in summer is a son who acts wisely. But he who sleeps in harvest is a son who acts shamefully."'},
        {sun: 'Mark 4:29\n"But when the crop permits, he immediately puts in the sickle, because the harvest has come."'},
        {bonus: 'John 4:37\n"For in this case the saying is true, One sows and another reaps (the harvest)."'}]},
{Immanuel: [
        {mon: 'Luke 1:26,30\n"Now in the sixth month the angel Gabriel was sent by God to a city called Nazareth. The angel said to her, Do not be afraid, Mary, for you have found favor with God."'},
        {tue: 'Luke 2:8,10\n"Now there were in the same region shepherds keeping watch over their flocks. And an angel said to them, Don\'t be afraid. I bring you good news of great joy."'}, 
        {wed: 'Luke 2:12\n"And this will be a sign for you; you will find a baby wrapped in cloths, and lying in a manger."'},
        {thu: 'Luke 2:15\n"The shepherds began saying to one another. \'Let us go straight to Bethlehem then, and see this thing that has happened which the Lord has made known to us.\’"'}, 
        {fri: 'Luke 2:16\n"And they came in haste and found their way to Mary and Joseph, and the baby as he lay in the manger."'},
        {sat: 'Luke 2:20\n"And the shepherds went back, glorifying and praising God for all that they had heard and seen, as had been told them."'},
        {sun: 'Luke 2:19 / Matthew 1:23\n"And Mary pondered all these things in her heart." / "Behold, the virgin shall bear a child, they shall call Him Immanuel - God with us."'},
        {bonus: 'Matthew 2:2\n"Where is He who has been born King of the Jews? We saw His star in the east, and have come to worship Him."'}]},
{Rewards: [
        {sun: 'Christ\'s Reward\n\nRevelation 22:12\n"Behold I am coming quickly and My reward is with me"'}, 
        {mon: 'The Crown of Victors\n\n1 Corinthians 9:24\n"Those who run in a race all run, but only one receives the prize (reward)."'},
        {tue: 'The Crown of Exultation\n\n1 Thessalonians 2:19\n"Who is our crown of exultation? It is you in the presence of Jesus at His coming."'}, 
        {wed: 'The Crown of Righteousness\n\n2 Timothy 4:8\n"...will be laid up for me and all who have loved His appearing."'},
        {thu: 'The Crown of Life\n\nRevelation 2:10\n"Be faithful until death, and I (Jesus) will give you the crown of life."'}, 
        {fri: 'The Crown of Glory\n\n1 Peter 5:4\n"When the Chief Shepherd appears, you will receive the crown of glory."'},
        {sat: 'The Crown of Thorns\n\nMatthew 27:29\n"And after weaving a crown of thorns they put it on Jesus\' head."'},
        {bonus: '1 Peter 3:15\n"But set apart Christ Jesus in your heart, always being ready to give a reason to everyone who asks you to give an account for the HOPE that is in you."'}]}];



//Blank Scripture Template:

// {: [
//         {mon: '\n""'},
//         {tue: '\n""'}, 
//         {wed: '\n""'},
//         {thu: '\n""'}, 
//         {fri: '\n""'},
//         {sat: '\n""'},
//         {sun: '\n""'},
//         {bonus: '\n""'}]},






let quoteMatrix = [
{Evil: [
        {sun: 'QUOTE:\n\n"God would rather transform the EVIL man than eradicate him."\n(Billy Graham)'}, 
        {mon: 'QUOTE:\n\n"Satan is EVIL in himself."\n(Peter Nii Korley)'},
        {tue: 'QUOTE:\n\n"It is in the close similarity between good and EVIL, right and wrong, that the danger lies."\n(Billy Graham)'}, 
        {wed: 'QUOTE:\n\n"If you want to chart the course of your life and live a fulfilling life, restrain and refrain your tongue from EVIL."\n(Justice Kojo Bentil)'},
        {thu: 'QUOTE:\n\n"The entry of light forces the exit of the darkness (EVIL)."\n(Mike Murdock)'}, 
        {fri: 'QUOTE:\n\n"EVIL is what disagrees with the provision God has made concerning a matter"\n(Justice Kojo Bentil)'},
        {sat: 'QUOTE:\n\n"This scripture says the love of money is the very root of Satan\'s operation. We can cut him off at the very root and destroy his base with the love of giving. Glory to God."\n(Kenneth M. Copeland)'},
        {bonus: 'QUOTE:\n\n"Anything good is hated by everything EVIL."\n(Mike Murdock)'}]},
{Faith: [
        {sun: 'QUOTE:\n\n"Faith is God\'s antidote for fear."\n(David Jeremiah)'}, 
        {mon: 'QUOTE:\n\n"If you only have a little ray of light, show out distinctly that you are for Jesus."\n(G.V. Wigam)'},
        {tue: 'QUOTE:\n\n"Doubt can strengthen your faith as God provides the answers to our most heartfelt questions."\n(David Jeremiah)'}, 
        {wed: 'QUOTE:\n\n"Faith is the engine driving all your actions."\n(John Blanchard)'},
        {thu: 'QUOTE:\n\n"Down through the centuries in times of trouble...God has brought courage to the hearts of those who love Him."\n(Billy Graham)'}, 
        {fri: 'QUOTE:\n\n"Assurance is a fruit that grows out of the root of faith"\n(Stephen Charnock)'},
        {sat: 'QUOTE:\n\n"Nothing needs to be added to Christ\'s finished work, and nothing can be added to Christ\'s finished work."\n(Francis Schaeffer)'},
        {bonus: 'QUOTE:\n\n"The Word of God is perfect and pure, it is truth itself."\n(Martin Luther)'}]},
{Forgiveness: [
        {sun: 'QUOTE:\n\n"To err is human, to forgive divine"\n(Alexander Pope)'}, 
        {mon: 'QUOTE:\n\n"Darkness cannot drive out darkness, only light can do that. Hate cannot drive out hate, only love."\n(Martin Luther King, Jr.)'},
        {tue: 'QUOTE:\n\n"Holding a grudge does not make you strong; it makes you bitter. Forgiving does not make you weak, it sets you free."\n(Dave Willis)'}, 
        {wed: 'QUOTE:\n\n"There is a nobility in compassion, a beauty in empathy, a grace in forgiveness."\n(John Connolly)'},
        {thu: 'QUOTE:\n\n"Forgiveness is a funny thing. It warms the heart and cools the sting."\n(William Arthur Ward)'}, 
        {fri: 'QUOTE:\n\n"The weak can never forgive. Forgiveness is the attribute of the strong."\n(Mahatmas Gandi)'},
        {sat: 'QUOTE:\n\n"A broken friendship that is mended through forgiveness can be even stronger than it ever was."\n(Stephan Richards)'}]},
 {Happiness: [
         {sun: '1 Chronicles 16:10\n"Glory in His holy name, let the heart of those who seek the Lord be glad."'}, 
        {mon: 'Proverbs 16:20\n"Blessed (happy) is he who trusts in the Lord."'},
        {tue: 'Romans 15:13\n"Now may the God of hope fill you with all joy and peace."'}, 
        {wed: 'Proverbs 14:21\n"Happy is he who is gracious to the poor."'},
        {thu: 'Psalm 132:9\n"Let your Godly people sing for joy."'}, 
        {fri: 'Psalm 144:5\n"How blessed (happy) are the people whose God is the Lord."'},
        {sat: 'Proverbs 29:18\n"Happy is he who keeps the law (God\'s Commandments)."'}]},
{Ark: [
        {sun: "Genesis 1:31\nThen God looked over all He had made, and He saw that it was very good."}, 
        {mon: "Romans 6:13\nSurrender your whole being to God to be used for righteous purpose."},
        {tue: "Isaiah 30:15\nIn repentance and rest is your salvation, in quietness and trust is your strength."}, 
        {wed: 'John 7:37\nJesus stood and cried out, "If anyone thirsts, let him come to Me and drink." (living water)'},
        {thu: "Proverb 23:17\nDo not let your heart envy sinners, but live in fear of the Lord."}, 
        {fri: "Proverb 21:23\nHe (the person) who guards his/her tongue guards their soul from trouble."},
        {sat: "1 John 4:16\nAnd so we know and rely on the love God has for us. God is love."}]},
{Worship: [
        {sun: "Psalm 2:11\nWorship the Lord with reverence and rejoice with trembling."}, 
        {mon: "Psalm 66:4\nAll the earth will worship You (God), and will sing praises to You."},
        {tue: "Isaiah 29:13\nPeople honor Me with their lips but their heart is far away from Me."}, 
        {wed: "John 4:24\nGod is spirit and those who worship Him must worship in spirit and truth."},
        {thu: "Exodus 34:14\nFor you shall not worship any other god, for the Lord, whose name is Jealous is a jealous God."}, 
        {fri: 'Matthew 4:10\nJesus said,"Begone Satan, for it is written: you shall worship the Lord your God, and serve Him only."'},
        {sat: "Revelation 4:11\nWorthy are You our Lord and our God, to receive glory and honor and power for You created all things."}]},
 {Promise: [
         {sun: "Revelation 10:1\nI saw another strong angel coming down out of heaven, clothed with a cloud and the rainbow was upon his head."}, 
        {mon: "2 Peter 3:13\nBut according to His (God\'s) promise, we are looking for new heavens and a new earth in which righteousness dwells."},
        {tue: "Psalm 29:2\nHonor the Lord in the glory. due His name; worship the Lord in the splendor of His holiness."}, 
        {wed: "Psalm 112:1,2\nPraise the Lord. How blessed is the man (person) who fears the Lord who greatly delights in His commandments, his descendants will be mighty on earth. The generations of the upright will be blessed."},
        {thu: "Genesis 8:21\nGod said, will never again curse the ground on account of man for the intent of Man\'s heart is evil and I will never again destroy every living thing as I have done."}, 
        {fri: 'Genesis 9:11\nI establish My covenant with you and all flesh shall never again be cut off by water of the flood."'},
        {sat: "Revelation 4:3\nAnd He who was sitting on the throne was like a jasper stone (crystal clear) and a sardius (blood red) in appearance, and there was a rainbow around the throne like an emerald in appearance."}]},
{Pray: [
        {sun: 'QUOTE:\n\n"All I know is that when I pray, coincidences happen, and when I don\'t pray they don\'t happen.\n(Dan Hayes)"'}, 
        {mon: 'QUOTE:\n\n"God warms His hands at man\'s heart when man prays."\n(John Masefield)'},
        {tue: 'QUOTE:\n\n"Any concerns too small to be turned into prayer is too small to be made into a burden."\n(Corrie Ten Boom)'}, 
        {wed: 'QUOTE:\n\n"In worship God imparts Himself to us."\n(C.S. Lewis)'},
        {thu: 'QUOTE:\n\n"Prayer is exhaling the spirit of man and inhaling the Spirit of God."\n(Edwin Keith)'}, 
        {fri: 'QUOTE:\n\n"I have lived long enough to thank God that not all my prayers have been answered."\n(Jean Ingelow)'},
        {sat: 'QUOTE:\n\n"If your day is hemmed in with prayer, it is less likely to come unravelled."\n(Cynthia Lewis)'}]},
{Spirit: [
        {sun: 'QUOTE:\n\n"Don\'t let obstacles along the road to eternity shake your confidence in God\'s promise. The Holy Spirit is God\'s seal that you will arrive."\n(David Jeremiah)'}, 
        {mon: 'QUOTE:\n\n"Were it not for the work of the Holy Spirit there would be no gospel, no faith, no church, no Christianity in the world at all."\n(J.I. Packer)'},
        {tue: 'QUOTE:\n\n"A sinner can no more repent and believe without the Holy Spirit\'s aid than he can create the world."\n(Charles Spurgeon)'}, 
        {wed: 'QUOTE:\n\n"The Holy Spirit can cast out the evil spirit of fear of man. He can make the coward brave."\n(Charles Spurgeon)'},
        {thu: 'QUOTE:\n\n"The Holy Spirit wants to convert the words of Scripture into transformed personalities."\n(David Jeremiah)'}, 
        {fri: 'QUOTE:\n\n"Without the Spirit of God, we can do nothing. We are as ships without wind. We are useless."\n(Charles Spurgeon)'},
        {sat: 'QUOTE:\n\n"The Bible without the Holy Spirit is a sundial by moonlight."\n(Dwight L. Moody)'}]},
{Study: [
        {sun: 'QUOTE:\n\n"If one thing lies at the basis of the whole biblical teaching about God, it is that God knows all things."\n(J.G. Gresham Machem)'}, 
        {mon: 'QUOTE:\n\n"This is the power of the Scriptures - personally they speak, if we will listen, heed them, and let them take over; they will transform us forever."\n(Mark Clark)'},
        {tue: 'QUOTE:\n\n"The gospel is not a doctrine of the tongue, but of life."\n(John Calvin)'}, 
        {wed: 'QUOTE:\n\n"Let God\'s promises shine on your problems."\n(Corrie Ten Boom)'},
        {thu: 'QUOTE:\n\n"The Word of God well understood and religiously obeyed, is the shortest route to spiritual perfection."\n(A.W. Tozer)'}, 
        {fri: 'QUOTE:\n\n"Dear Father, teach me to hold fast to the Word of life. Give me a hunger for Scripture."\n(Kay Arthur)'},
        {sat: 'QUOTE:\n\n"Christ could come at any moment. I believe that with all my heart - not because of what I read in the newspapers, but because of what I read in Scripture."\n(John McArthur)'}]},
{Sword: [
        {sun: 'QUOTE:\n\n"If we are instant in prayer and faithful in it, every little circumstance awakes the disposition to pray, and desires and words are always ready."\n(Felix Neff)'}, 
        {mon: 'QUOTE:\n\n"Our enemies are on every side, and so must our armor be."\n(William Goral)'},
        {tue: 'QUOTE:\n\n"The truth of Scripture demolishes speculation."\n(R.C. Sproul)'}, 
        {wed: 'QUOTE:\n\n"Liberty has brought us the freedom to be a slave of righteousness."\n(Charles Ryrie)'},
        {thu: 'QUOTE:\n\n"Jesus didn\'t commit the gospel to an advertising agency; he commissioned disciples."\n(Joseph Bayly)'}, 
        {fri: 'QUOTE:\n\n"Faith is the gaze of a soul upon a saving God."\n(A.W. Tozer)'},
        {sat: 'QUOTE:\n\n"When we fill our minds with Scripture and live accordingly to its principles, Satan\'s schemes lose their power over us."\n(Charles Stanley)'}]},
{Thankful: [
        {sun: 'QUOTE:\n\n"Thanksgiving day is a jewel to set in the hearts of honest men; but be careful that you do not take the day and leave out the gratitude."\n(E.P. Powell)'}, 
        {mon: 'QUOTE:\n\n"The unthankful heart discovers no mercies; but the thankful heart will find, in every hour, some heavenly blessings."\n(Henry Ward Beecher)'},
        {tue: 'QUOTE:\n\n"So once in every year we throng upon a day apart, to praise the Lord with feast and song with thankfulness of heart."\n(Arthur Guiterman)'}, 
        {wed: 'QUOTE:\n\n"Reflect upon your present blessings, of which every man has plenty; not on your past misfortunes, of which all men have some."\n(Charles Dickens)'},
        {thu: 'QUOTE:\n\n"In happy moments, praise God. In difficult moments, seek God. In quiet moments, worship God. In painful moments, trust God. Every moment, thank God."\n(Rick Warren)'}, 
        {fri: 'QUOTE:\n\n"Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow."\n(Melody Beattie)'},
        {sat: 'QUOTE:\n\n"God is pleased with no music below so much as with the thankful songs of relieved widows and supported orphans; of rejoicing, comforted, and thankful persons."\n(Jeremy Taylor)'},
        {bonus: 'QUOTE:\n\n"Perhaps it takes a purer faith to praise God for unrealized blessings than for those we once enjoyed or those we enjoy now."\n(A.W. Tozer)'}]},
{Think: [
        {sun: 'QUOTE:\n\n"There comes a time when one must take a position that is neither safe nor politic nor popular, but he must take it because concience tells him it is right."\n(Martin Luther King, Jr.)'}, 
        {mon: 'QUOTE:\n\n"Integrity is doing the right thing, even when no one is watching."\n(C.S. Lewis)'},
        {tue: 'QUOTE:\n\n"Praise, like sunshine, helps all things grow."\n(Croft M. Pentz)'}, 
        {wed: 'QUOTE:\n\n"Knowing what\'s right doesn\'t mean much unless you do what\'s right."\n(Theodore Roosevelt)'},
        {thu: 'QUOTE:\n\n"For I am persuaded that the Lord has more truth and light yet to break forth from His holy word."\n(John Robinson)'}, 
        {fri: 'QUOTE:\n\n"I hope I shall possess firmness and virtue enough to maintain what I consider the most enviable of all titles, the character of an honest man."\n(George Washington)'},
        {sat: 'QUOTE:\n\n"The right kind of heart is a kind heart like God\'s."\n(Unknown)'},
        {bonus: 'QUOTE:\n\n"The Word of God is perfect and pure, it is truth itself."\n(Martin Luther)'}]},
{Time: [
        {sun: 'QUOTE:\n\n"Life is hard - but God is good, and heaven is real."\n(Billy Graham)'}, 
        {mon: 'QUOTE:\n\n"The devil is not afraid of a Bible that has dust on it."\n(Anonymous)'},
        {tue: 'QUOTE:\n\n"The object of a new year is not that we should have a new year, but rather that we should have a new soul."\n(G.K. Chesterton)'}, 
        {wed: 'QUOTE:\n\n"Life can only be enjoyed as one acquires a true perspective of life and death and of the real purpose of life."\n(Spiros Zodhiutes)'},
        {thu: 'QUOTE:\n\n"The year is made up of minutes. Let these be watched as having been dedicated to God."\n(G. Campbell Morgan)'}, 
        {fri: 'QUOTE:\n\n"Look up in simple faith to the crucified Savior, who alone can lift you to a higher plane of life."\n(Ruth Paxson)'},
        {sat: 'QUOTE:\n\n"God has staked His reputation on the work of Jesus Christ in the souls of men and women whom He has saved and sanctified."\n(Oswald Chambers)'},
        {bonus: 'QUOTE:\n\n"The Word of God is perfect and pure, it is truth itself."\n(Martin Luther)'}]},
{Hope: [
        {sun: 'QUOTE:\n\n"Do not look to HOPE, but to the source of your HOPE."\n(Charles Spurgeon)'}, 
        {mon: 'QUOTE:\n\n"If we are saved by grace alone, our salvation is a constant source of amazed delight...we don\'t take ourselves seriously and we\'re full of HOPE for the world."\n(Tim Keller)'},
        {tue: 'QUOTE:\n\n"True faith is ever connected to HOPE."\n(John Calvin)'}, 
        {wed: 'QUOTE:\n\n"Let us be alert to the season in which we are living. It is the season of the blessed HOPE."\n(A.W. Tozer)'},
        {thu: 'QUOTE:\n\n"Find ways of using your own platform to share the HOPE of Christ."\n(David Jeremiah)'}, 
        {fri: 'QUOTE:\n\n"All great things are simple and many can be expressed in a single word: freedom, justice, honor, duty, mercy, and HOPE."\n(Winston Churchill)'},
        {sat: 'QUOTE:\n\n"Where there is no vision, there is no HOPE!"\n(George Washington Carver)'},
        {bonus: 'QUOTE:\n\n"Jesus gives us HOPE because He keeps us company, has a vision, and knows the way we should go."\n(Max Lucado)'}]},
{Love: [
        {sun: 'QUOTE:\n\n"I was sinking deep in sin ... love lifted me."\n(James Rowe)'}, 
        {mon: 'QUOTE:\n\n"When we focus on our gratitude, the tide of disappointment goes out and the tide of love rushes in."\n(Kristen Armstrong)'},
        {tue: 'QUOTE:\n\n"God does not give us power to imitate Him. He gives us His very self (love)."\n(Oswald Chambers)'}, 
        {wed: 'QUOTE:\n\n"The true measure of God\'s love is that He (God) loves without measure."\n(Unknown)'},
        {thu: 'QUOTE:\n\n"O that I may ascend in a glow of love to Him to be with Him forever."\n(Ebenseger Ernskinde)'}, 
        {fri: 'QUOTE:\n\n"True love is always costly!"\n(Billy Graham)'},
        {sat: 'QUOTE:\n\n"Where love is, God is."\n(Henry Drummond)'},
        {bonus: 'QUOTE:\n\n"God\'s love falls gently like April showers. Don\'t fail to receive the refreshment He offers today."\n(David Jeremiah)'}]},
{Letters: [
        {sun: 'QUOTE:\n\n"God loves each of us as if there were only one of us."\n(Augustine)'}, 
        {mon: 'QUOTE:\n\n"Lord, I choose to forgive this person, but I need your help! Take from me my anger enable me with your super-natural power, to love this person."\n(Todd Nettleton)'},
        {tue: 'QUOTE:\n\n"True love is always costly."\n(Billy Graham)'}, 
        {wed: 'QUOTE:\n\n"Whether Jesus calms the storm or calms us in the storm, His love is the same, and His grace is enough."\n(Shelia Walsh)'},
        {thu: 'QUOTE:\n\n"Either directly or indirectly every providence has a tendency to the spiritual good of those who love God."\n(Matthew Henry)'}, 
        {fri: 'QUOTE:\n\n"Where love is, God is."\n(Henry Drummond)'},
        {sat: 'QUOTE:\n\n"The true measure of God\'s love is that He loves without measure."\n(Unknown)'},
        {bonus: 'QUOTE:\n\n"When we focus on our gratitude, the tide of disappointment goes out and the tide of love rushes in."\n(Kristin Armstrong)'}]},
{Grace: [
        {sun: 'QUOTE:\n\n"My God, how excellent Thy grace whence all our hope and comfort spring."\n(Isaac Watts)'},
        {mon: 'GRACE is:\nG = God\'s\nR = Riches\nA = At\nC = Christ\'s\nE = Expense'}, 
        {tue: 'QUOTE:\n\n"The spiritual freedom of which Christ spoke comes only by grace and truth."\n(David Jeremiah)'},
        {wed: 'QUOTE:\n\n"There is never a day in any man\'s life but that he is dependent upon the grace of God for power and the blood of Jesus for cleansing."\n(Alan Redpath)'}, 
        {thu: 'QUOTE:\n\n"God\'s strength can only work in our weakness."\n(Andrew Murry)'},
        {fri: 'QUOTE:\n\n"In the darkness of our miseries, the grace of God shines more brightly."\n(John Calvin)'}, 
        {sat: 'QUOTE:\n\n"No evil can resist grace forever."\n(Brennan Manning)'},
        {bonus: 'QUOTE:\n\n"Grace, grace, God\'s grace, grace that is greater than all our sin."\n(Julia H. Johnston)'}]},
{Wisdom: [
        {mon: 'QUOTE:\n\n"Wisdom opens the eyes both to the glories of heaven and to the hollowness of earth."\n(J.A. Motyer)'},
        {tue: 'QUOTE:\n\n"Wise men talk because they have something to say, fools, because they have to say something."\n(Plato)'}, 
        {wed: 'QUOTE:\n\n"The chief means for attaining wisdom, and suitable gifts for the ministry, are the Holy Scripture, and prayer."\n(John Newton)'},
        {thu: 'QUOTE:\n\n"Christ is the true light of the world; it is through Him alone that true wisdom is imparted to the mind."\n(Jonathan Edwards)'}, 
        {fri: 'QUOTE:\n\n"Never argue with a fool. Onlookers may not be able to tell the difference."\n(Mark Twain)'},
        {sat: 'QUOTE:\n\n"Patience is a companion of wisdom."\n(Augustine)'},
        {sun: 'QUOTE:\n\n"Some view the Spiritual quest as one of seeking wisdom, knowledge, and understanding - a learning process."\n(Alice Camille)'},
        {bonus: 'QUOTE:\n\n"For it is not our natural reasoning powers that will guide us correctly or give us right judgment in all things. No, Christ alone is our wisdom."\n(Al Bryant)'}]},
{Resurrection: [
        {mon: 'QUOTE:\n\n"The Lamb\'s Book of Life is the book of Jesus Christ in which are entered the names of those who have received His eternal life."\n(Tim LaHaye)'},
        {tue: 'QUOTE:\n\n"Believers are living stones connected together with Christ as the Cornerstone."\n(Unknown)'}, 
        {wed: 'QUOTE:\n\n"Christ is the ocean, in which every drop is infinite compassion."\n(Henry Law)'},
        {thu: 'QUOTE:\n\n"Life will betray you, but God never will."\n(Unknown)'}, 
        {fri: 'QUOTE:\n\n"It was Christ who willingly went to the cross and it was our sins that took Him there."\n(Franklin Graham)'},
        {sat: 'QUOTE:\n\n"God\'s mercy and grace gives me hope for myself and for our world."\n(Billy Graham)'},
        {sun: 'QUOTE:\n\n"Let\'s keep our chin up and our knees down- we\'re on the victory side."\n(Alan Redpath)'},
        {bonus: 'QUOTE:\n\n"Alleluia, how people cheer and palm leaves rustle as the King draws near."\n(John Beavis)'}]},
{Obey: [
        {mon: 'QUOTE:\n\n"Your faith level is determined by your obedience level."\n(Jack Hyles)'},
        {tue: 'QUOTE:\n\n"Wicked men obey from fear; good men from love."\n(Augustine)'}, 
        {wed: 'QUOTE:\n\n"Joy, not grit, is the hallmark of holy obedience. We need to be lighthearted in what we do. It is a cheerful revolt against self and pride."\n(Richard J. Foster)'},
        {thu: 'QUOTE:\n\n"A ton of prayer will not produce what an ounce of obedience will."\n(Ed Cole)'}, 
        {fri: 'QUOTE:\n\n"Truth without obedience is hypocrisy; Obedience without truth is legalism."\n(Jack Wellman)'},
        {sat: 'QUOTE:\n\n"Maturity comes from obedience, not necessarily from age."\n(Leonard Ravenhill)'},
        {sun: 'QUOTE:\n\n"God\'s commands are designed to guide you to life\'s very best."\n(Henry Blackaby)'},
        {bonus: 'QUOTE:\n\n"You cannot obey God without your obedience spilling out in a blessing to all those around you."\n(Adrian Rogers)'}]},
{Prayer: [
        {mon: 'QUOTE:\n\n"If you are too busy to pray, then you are too busy."\n(W.E. Sangster)'},
        {tue: 'QUOTE:\n\n"Lord and Savior, true and kind, be the master of my mind; Bless and guide and strengthen still, all my powers of thought and will."\n(Handley Moule)'}, 
        {wed: 'QUOTE:\n\n"Before we can pray, \'Lord, Thy kingdom come,\' we must be willing to pray, \'Lord, my kingdom go.\'"\n(Alan Redpath)'},
        {thu: 'QUOTE:\n\n"Reading the Bible is not like reading any other book in the world. It\'s the only book able to conform us to the image of its author."\n(David Jeremiah)'}, 
        {fri: 'QUOTE:\n\n"The universe in its immensity was especially created for us humans so that we could see and appreciate the glory and the power of God."\n(Werner Gitt)'},
        {sat: 'QUOTE:\n\n"When our bodies need energy, we eat food. But when our souls need hope, we are nourished by God\'s precious and very great promises."\n(Jon Bloom)'},
        {sun: 'QUOTE:\n\n"The glory of Christianity is to conquer by forgiveness."\n(William Blake)'},
        {bonus: 'QUOTE:\n\n"Satan and his demons never, never act against God\'s people without the permission of God."\n(John MacArthur)'}]},
{Patriotic: [
        {mon: 'QUOTE:\n\n"Truth will ultimately prevail where pain is taken to bring it to light."\n(George Washington)'},
        {tue: 'QUOTE:\n\n"Honesty is not only the first step to greatness, it is greatness itself."\n(Christian Bovee)'}, 
        {wed: 'QUOTE:\n\n"In the absence of justice, what is sovereignty but organized robbery?"\n(Augustine)'},
        {thu: 'QUOTE:\n\n"The best things in life are tax free."\n(Joseph Bronkowski)'}, 
        {fri: 'QUOTE:\n\n"Maturity comes from obedience, not necessarily from age."\n(Leonard Ravenhill)'},
        {sat: 'QUOTE:\n\n"Where there is no law, there is no liberty."\n(Benjamin Rush)'},
        {sun: 'QUOTE:\n\n"May that Being Who is supreme over all, ... continue His blessing upon this nation and its government ... consistent with the ends of His providence."\n(John Quincy Adams)'},
        {bonus: 'QUOTE:\n\n"No people will tamely surrender their liberties, nor can any be easily subdued, when knowledge is diffused and virtue is preserved."\n(John Adams)'}]},
{Reborn: [
        {mon: 'QUOTE:\n\n"If you\'re really born again, there\'s nothing can separate you from God."\n(William Marrion Branham)'},
        {tue: 'QUOTE:\n\n"Until a man is born again, his praise is mere noise or religious entertainment. Only the living can praise the Lord."\n(David O. Oyedepo)'}, 
        {wed: 'QUOTE:\n\n"The highest form of deliverance is to be born again."\n(Unknown)'},
        {thu: 'QUOTE:\n\n"The spiritual life is a gift of the Living Spirit. The spiritual is no mere development of the natural man. He is a new creation born from above."\n(Henry Drummond)'}, 
        {fri: 'QUOTE:\n\n"As is true of man who is born naturally and receives a human nature from his parents, so man born anew receives a new nature, a new capacity for service and devotion to God."\n(John F. Walvoord)'},
        {sat: 'QUOTE:\n\n"Eternal life is not a peculiar feeling inside. If you are born again, eternal life is that quality of life that you possess right now."\n(Major Ian Thomas)'},
        {sun: 'QUOTE:\n\n"Faith is the evidence of new birth, not the cause of it."\n(John Piper)'},
        {bonus: 'QUOTE:\n\n"Fully born again in the Lord brings a total separation from believers and unbelievers."\n(Peter Korley)'}]},
{Promises: [
        {mon: 'FAITH:\n\n"Faith begins with a backward look at the cross, but it lives with a forward look at the promises."\n(John Piper)'},
        {tue: 'VIRTUE:\n\n"Gratitude is the mother of all virtues."\n(G.K. Chesterton)'}, 
        {wed: 'KNOWLEDGE:\n\n"The end of all learning is to know God, and out of that knowledge to love and imitate Him."\n(John Milton)'},
        {thu: 'SELF-CONTROL:\n\n"I am a spiritual being... after this body is dead my spirit will soar. I choose self-control... I will be impassioned by my faith... I choose self-control."\n(Max Lucado)'}, 
        {fri: 'PERSERVERANCE:\n\n"By perseverance the snail reached the ark."\n(Charles Spurgeon)'},
        {sat: 'GODLINESS:\n\n"The key to godliness is not more knowledge but more obedience."\n(Woodrow Kroll)'},
        {sun: 'KINDNESS:\n\n"The greatest thing a man can do for his Heavenly Father is to be kind to some of His other children."\n(Henry Drummond)'},
        {bonus: 'LOVE:\n\n"Not all of us can do great things. But we can do small things with great love."\n(Mother Teresa)'}]},
{Satan: [
        {mon: 'QUOTE:\n\n"As long as Satan is loose in the world and our hearts are dominated by his evil passions, it will never be easy or popular to be a follower of Christ."\n(Billy Graham)'},
        {tue: 'QUOTE:\n\n"What is Satan? He is anything contrary to the Word of God."\n(William Marrion Branham)'}, 
        {wed: 'QUOTE:\n\n"You cannot make men good by law."\n(C.S. Lewis)'},
        {thu: 'QUOTE:\n\n"God\'s followers need to know the truth He sets forth in His Word so that we can confidently discern between His truth and Satan\'s lies."\n(Billy Graham)'}, 
        {fri: 'QUOTE:\n\n"Neither the devil nor the world, nor even our own evil heart can compel us to sin. It must be by our own consent and will."\n(Billy Graham)'},
        {sat: 'QUOTE:\n\n"The first time (Christ) came to slay sin in man. The second time He will come to slay men in sin."\n(A.W. Pink)'},
        {sun: 'QUOTE:\n\n"The humblest individual exerts some influence, either good or evil, upon others."\n(Henry Ward Beecher)'},
        {bonus: 'QUOTE:\n\n"There is a Holy Trinity, and there is likewise a Trinity of Evil."\n(A.W. Pink)'}]},
{Harvest: [
        {mon: 'QUOTE:\n\n"Your future is a harvest produced by the seed you are willing to sow."\n(Mike Murdock)'},
        {tue: 'QUOTE:\n\n"An uncommon seed always creates an uncommon harvest."\n(Mike Murdock)'}, 
        {wed: 'QUOTE:\n\n"When you ask God for a harvest, He will always ask you for a seed."\n(Mike Murdock)'},
        {thu: 'QUOTE:\n\n"The quality of your seed determines the quality of your harvest."\n(Mike Murdock)'}, 
        {fri: 'QUOTE:\n\n"Honor becomes your seed before you reap it as a harvest."\n(Mike Murdock)'},
        {sat: 'QUOTE:\n\n"Your seed is anything that benefits another, your harvest is anything that benefits you."\n(Mike Murdock)'},
        {sun: 'QUOTE:\n\n"When God talks to you about a seed, He has a harvest on His mind."\n(Mike Murdock)'},
        {bonus: 'QUOTE:\n\n"If what you hold in your hand is not enough to be your harvest, it must be your seed."\n(Mike Murdock)'}]},
{Immanuel: [
        {mon: '<div class="lyric-container"><span>"Silent Night, Holy Night" <span class="tooltip">Lyrics<span class="tooltiptext">"Silent Night, Holy Night"\n\nSilent night, Holy night\nAll is calm, all is bright\nRound yon virgin, mother and child\nHoly infant, so tender and mild\nSleep in heavenly peace,\nSleep in heavenly peace.\n\nSilent night, Holy night\nShepherds quake, at the sight\nGlories stream from heaven afar\nHeavenly, hosts sing Hallelujah.\nChrist the Savior is born,\nChrist the Savior is born.\n\nSilent night, Holy night\nSon of God, love\'s pure light\nRadiant beams from thy holy face\nWith the dawn of redeeming grace,\nJesus, Lord at thy birth\nJesus, Lord at thy birth\nJesus, Lord at thy birth\nJesus, Lord at thy birth.\n\nSongwriters: Traditional Song.</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas1/13Silent_Night.mp3" class="flashplNEW" id="audio_13" title="Play"></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas1/13Silent_Night.mp3" preload="none" controls="" class="audiopl" id="audiopl_13"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'},
        {tue: '<div class="lyric-container"><span>"Joy To The World" <span class="tooltip">Lyrics<span class="tooltiptext">"Joy To The World"\n\nJoy to the world, the Lord is come!\nLet earth receive her King;\nlet ev\’ry heart prepare him room\nand heav\’n and nature sing,\nand heav\’n and nature sing,\nand heav\’n, and heav\’n and nature sing.\n\nJoy to the earth, the Savior reigns!\nLet men their songs employ,\nwhile fields and floods, rocks, hills, and plains,\nrepeat the sounding joy,\nrepeat the sounding joy,\nrepeat, repeat the sounding joy.\n\nNo more let sins and sorrows grow\nnor thorns infest the ground;\nhe comes to make his blessings flow\nfar as the curse is found,\nfar as the curse is found,\nfar as, far as the curse is found.\n\nHe rules the world with truth and grace\nand makes the nations prove\nthe glories of his righteousness\nand wonders of his love,\nand wonders of his love,\nand wonders, wonders of his love.\n\nSource: Christian Worship (2021): Hymnal #353</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas1/03Joy_to_the_World.mp3" class="flashplNEW" id="audio_3" title="Play"></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas1/03Joy_to_the_World.mp3" preload="none" controls="" class="audiopl" id="audiopl_3"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'}, 
        {wed: '<div class="lyric-container"><span>"Away In A Manger" <span class="tooltip">Lyrics<span class="tooltiptext">"Away In A Manger"\n\nAway in a manger\nNo crib for a bed\nThe little Lord Jesus\nLaid down His sweet head\nThe stars in the bright sky\nLooked down where He lay\nThe little Lord Jesus\nAsleep on the hay\n\nThe cattle are lowing\nThe Baby awakes\nBut little Lord Jesus\nNo crying He makes\nI love You, Lord Jesus\nLook down from the sky\nAnd stay by my side\nUntil morning is nigh\n\nBe near me, Lord Jesus\nI ask You to stay\nClose by me forever\nAnd love me I pray\nBless all the dear children\nIn Your tender care\nAnd fit us for heaven\nTo live with You there\n\n</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas2/13Away_in_a_Manger.mp3" class="flashplNEW" id="audio_26" title="Play"></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas2/13Away_in_a_Manger.mp3" preload="none" controls="" class="audiopl" id="audiopl_26"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'},
        {thu: '<div class="lyric-container"><span>"O Little Town Of Bethlehem" <span class="tooltip">Lyrics<span class="tooltiptext">"O Little Town Of Bethlehem"\n\nOh little town of Bethlehem, how still we see thee lie\nAbove thy deep and dreamless sleep the silent stars go by\nYet in thy dark streets shineth, the everlasting light\nThe hopes and fears of all the years are met in thee tonight.\n\nFor Christ is born of Mary, and gathered all above\nWhile mortals sleep the angels keep their watch of wondering love\nOh morning stars together, proclaim thy holy birth.\nAnd praises sing to God the king, and peace to men on earth.\n\nOh little town of Bethlehem, how still we see thee lie\nAbove thy deep and dreamless sleep the silent stars go by\nYet in thy dark streets shineth, the everlasting light\nThe hopes and fears of all the years are met in thee tonight.\n</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas3/01O_Little_Town_of_Bethlehem.mp3" class="flashplNEW" id="audio_27" title="Play"></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas3/01O_Little_Town_of_Bethlehem.mp3" preload="none" controls="" class="audiopl" id="audiopl_27"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'}, 
        {fri: '<div class="lyric-container"><span>"Hark, The Herald Angels Sing" <span class="tooltip">Lyrics<span class="tooltiptext">"Hark! The Herald Angels Sing"\n\nHark! The herald angels sing\n"Glory to the new-born king\nPeace on earth and mercy mild\nGod and sinners reconciled"\nJoyful all ye nations rise\nJoin the triumph of the skies\nWith angelic host proclaim\n"Christ is born in Bethlehem"\nHark! The herald angels sing\n"Glory to the new-born king"\n\nHail the heaven-born Prince of Peace!\nHail the Sun of Righteousness!\nLight and life to all He brings\nRisen with healing in His wings\nMild He lays His glory by\nBorn that man no more may die\nBorn to raise the sons of earth\nBorn to give them second birth\nHark! The herald angels sing\n"Glory to the new-born king"\n\n</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas2/01Hark_The_Herald_Angels_Sing.mp3" class="flashplNEW" id="audio_14" title="Play"></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas2/01Hark_The_Herald_Angels_Sing.mp3" preload="none" controls="" class="audiopl" id="audiopl_14"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'},
        {sat: '<div class="lyric-container"><span>"The First Noel" <span class="tooltip">Lyrics<span class="tooltiptext">"The First Noel"\n\nThe first Noel the angel did say\nwas to certain poor shepherds in fields as they lay—\nin fields where they lay keeping their sheep,\non a cold winter’s night that was so deep.\n\nRefrain:\nNoel, Noel, Noel, Noel,\nborn is the King of Israel.\n\nThey looked up and saw a star\nshining in the east, beyond them far,\nand to the earth it gave great light,\nand so it continued both day and night. [Refrain]\n\n</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas1/10The_First_Nowell_-_The_First_Noel.mp3" class="flashplNEW" id="audio_10" title="Play" style=""></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas1/10The_First_Nowell_-_The_First_Noel.mp3" preload="auto" controls="" class="audiopl" id="audiopl_10"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'},
        {sun: '<div class="lyric-container"><span>"O Come, O Come Immanuel" <span class="tooltip">Lyrics<span class="tooltiptext">"O come, O come, Immanuel"\n\nO come, O come, Immanuel,\nand ransom captive Israel\nthat mourns in lonely exile here\nuntil the Son of God appear.\n\nRefrain:\nRejoice! Rejoice! Immanuel\nshall come to you, O Israel.\n\nO come, O Wisdom from on high,\nwho ordered all things mightily;\nto us the path of knowledge show\nand teach us in its ways to go. Refrain\n\nO come, O King of nations, bind\nin one the hearts of all mankind.\nBid all our sad divisions cease\nand be yourself our King of Peace. Refrain\n\nPsalter Hymnal (Gray)</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas2/09O_Come_O_Come_Immanuel.mp3" class="flashplNEW" id="audio_22" title="Play"></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas2/09O_Come_O_Come_Immanuel.mp3" preload="none" controls="" class="audiopl" id="audiopl_22"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'},
        {bonus: '<div class="lyric-container"><span>"We Three Kings Of Orient Are" <span class="tooltip">Lyrics<span class="tooltiptext">"We Three Kings Of Orient Are"\n\nWe three kings of Orient are;\nbearing gifts we traverse afar,\nfield and fountain, moor and mountain,\nfollowing yonder star.\n\nRefrain:\nO star of wonder, star of light,\nstar with royal beauty bright,\nwestward leading, still proceeding,\nguide us to thy perfect light.\n\nBorn a King on Bethlehem\'s plain,\ngold I bring to crown him again,\nKing forever, ceasing never,\nover us all to reign. [Refrain]\n\n</span></span></span></div><br><a href="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas3/11The_Three_Kings_of_Orient_Are.mp3" class="flashplNEW" id="audio_37" title="Play" style=""></a><audio src="https://media.virtualsheetmusic.com/Mp3/Miscellaneous/Christmas3/11The_Three_Kings_of_Orient_Are.mp3" preload="auto" controls="" class="audiopl" id="audiopl_37"></audio>\n<span>Music courtesy of: <a href="https://www.virtualsheetmusic.com/downloads/ChristmasMidi.html">Virtual Sheet Music</a></span>'}]},
{Rewards: [
        {sun: 'Christ\'s Reward\n\nRevelation 22:12\n"Behold I am coming quickly and My reward is with me"'}, 
        {mon: 'The Crown of Victors\n\n1 Corinthians 9:24\n"Those who run in a race all run, but only one receives the prize (reward)."'},
        {tue: 'The Crown of Exultation\n\n1 Thessalonians 2:19\n"Who is our crown of exultation? It is you in the presence of Jesus at His coming."'}, 
        {wed: 'The Crown of Righteousness\n\n2 Timothy 4:8\n"...will be laid up for me and all who have loved His appearing."'},
        {thu: 'The Crown of Life\n\nRevelation 2:10\n"Be faithful until death, and I (Jesus) will give you the crown of life."'}, 
        {fri: 'The Crown of Glory\n\n1 Peter 5:4\n"When the Chief Shepherd appears, you will receive the crown of glory."'},
        {sat: 'The Crown of Thorns\n\nMatthew 27:29\n"And after weaving a crown of thorns they put it on Jesus\' head."'},
        {bonus: '1 Peter 3:15\n"But set apart Christ Jesus in your heart, always being ready to give a reason to everyone who asks you to give an account for the HOPE that is in you."'}]}];

//Blank Quote Template:

//{: [
        //{mon: 'QUOTE:\n\n""\n()'},
        //{tue: 'QUOTE:\n\n""\n()'}, 
        //{wed: 'QUOTE:\n\n""\n()'},
        //{thu: 'QUOTE:\n\n""\n()'}, 
        //{fri: 'QUOTE:\n\n""\n()'},
        //{sat: 'QUOTE:\n\n""\n()'},
        //{sun: 'QUOTE:\n\n""\n()'},
        //{bonus: 'QUOTE:\n\n""\n()'}]},



